The-Mu-Foundation/Mutorials

- database/models/user.js
- routes/private.js
- routes/public.js
- utils/functions/database.js
- utils/functions/siteAlgorithms.js
- views/partials/components/experienceBar.ejs
- views/partials/components/siteStats.ejs
- views/private/homepage.ejs
- views/private/profile.ejs
- views/public/index.ejs
- Experience bar backend: for experience E and level L, dE/dL = 100L^1.25 (the level would be the integral of the derivative)
- Experience is obtained by answering questions - initial value of +=q.rating for correct, +=q.rating/2 for wrong, +=q.rating/20 for repeat question
- Experience bar shows on profiles and on homepage
- Semi-related side tweak of tag counting (fixed double counting bug)
> New Experience Bar Feature

- node_modules/connect-flash/package.json
- routes/public.js
- views/public/signup.ejs
lmk how it is
also, what code formatter do you guys use? pls tell
> fixed #205

- routes/private.js
- views/private/settings.ejs
Fixed issue #233, and also separated the preferences form for future usage. Also, formatted the code that was edited in this PR.
> Settings page cleanup

- utils/functions/database.js
> Uh oh, stinky

- routes/public.js
Totally didn't forget to do that the first time.
Anyways, I think this also fixes issue #236. Hopefully
> Fixed duplicate user detection AND removed debug logs

- utils/constants/tags.js
- views/partials/components/aboutMutorials.ejs
- views/partials/components/iconBar.ejs
- views/partials/components/siteStats.ejs
- views/partials/header.ejs
- views/partials/navigationPrivate.ejs
- views/partials/navigationPublic.ejs
- views/private/homepage.ejs
- views/public/index.ejs
Done for 3 main pages - index page and aboutmutorials when unauthed, and homepage for authed
> Mobile optimization

- utils/constants/subjects.js
New units:
Atoms Molecules and Ions
Solutions
Physical Chemistry
> Updated with new chem units

- routes/private.js
- views/private/settings.ejs
changing password now checks to make sure current password is entered correctly
> check for cur pw

- routes/public.js
removed the quickfix on year of birth and fixed the check for yob length to be equal to 4
> fixed check on year of birth for registering

- routes/public.js
- utils/functions/passport.js
- views/public/signin.ejs
- views/public/signup.ejs
- remove hcaptcha
- remove email validation and forgot password from public access
- remove a frontend link
Whoever looks at this ought to check whether I've actually done what I've promised :) run this on localhost and look for any mentions of these features.
> disable email confirmation and forgot password

- views/partials/components/aboutMutorials.ejs
added some qualifications to about us page
> added qualifications

- utils/constants/tags.js
> new chem tag

- views/partials/header.ejs
- views/public/signup.ejs
Google Ads conversion tracking added
> google ads conversion tracking

- .eslintrc.yml
- .github/workflows/run-tests.yml
- index.js
- package-lock.json
- package.json
- routes/admin.js
- routes/contributors.js
- routes/public.js
- routes/settings.js
- routes/stats.js
- routes/train.js
- utils/functions/admin.js
- utils/functions/database.js
- utils/functions/emailValidation.js
- utils/functions/mongo.js
- utils/functions/webhook.js
Fixes #390
I've added the `no-vars` rule as a first rule and fixed the errors that came out of it.
I've also added a workflow to run linting on future PRs
> Adds eslint workflow

- routes/train.js
- views/admin/train/addQuestion.ejs
Clarifying question input page
> quick clarification

- views/admin/train/editQuestion.ejs
`./views/admin/train/editQuestion.ejs` now passes question data through an element attribute as opposed to directly through the script. This fixes backslash escaping issues and the js-injection vulnerability.
> Fix LaTeX issues

- utils/constants/presets.js
not complete, editing some units
> Update Unit selections for Physics Courses

- routes/settings.js
- views/private/settings.ejs
> Confirm pwd on del issue 256

- routes/settings.js
users can now leave bio empty after setting it to something
> about page bio hotfix

- views/partials/navigationPrivate.ejs
- views/private/references/home.ejs
https://mutorials-test-app.herokuapp.com/homepage
- about us removed from references page
- references removed from train dropdown
- references added to nav bar
> modified nav

- routes/private.js
- utils/functions/database.js
- views/partials/components/search.ejs
- views/private/homepage.ejs
- views/private/search.ejs
- views/public/index.ejs
- Replaced the search button on the homepage with a component
> Fix search bugs

- .gitignore
- routes/train.js
- views/private/train/rush.ejs
this prevents the cheat to get an infinite score
> fix autoanswer exploit

- routes/train.js
(prevent users from getting a easier question than their level or submitting more than once)
> even more security (#445)

- routes/admin.js
- views/admin/train/editQuestion.ejs
Reverts The-Mu-Foundation/Mutorials#465, bug with editquestion
> Revert "making sure admins type in their admin id correctly when reviewing a question"

- routes/private.js
- views/partials/components/search.ejs
- views/partials/header.ejs
https://github.com/The-Mu-Foundation/Mutorials/issues/452
> Add checkbox selection in search page #452

- utils/functions/siteAlgorithms.js
…rating fluctuations more difficult, make rating spread of questions significantly higher, make strengths/weaknesses more difficult to obtain
> rating changes

- utils/constants/sitesettings.js
- views/private/homepage.ejs
Tried to fix "Don’t show subjects with no rating", instead of hiding them I thought it would be better to just show "no rating"
> changed rating 0 to 'no rating' when there is no rating

- views/public/teamV2.ejs
> Add 23-24 board

- package-lock.json
- views/public/indexV2.ejs
Change styling for hiring modal
> Clean up hiring modal

- index.js
- package.json
- vercel.json
- views/partials/headV2.ejs
See `vercel.json` for the main bits
- https://vercel.com/docs/projects/project-configuration#buildcommand
- https://stackoverflow.com/questions/72133185/deploy-an-express-server-that-uses-express-static-to-serve-a-build-folder-to-ver
> Make Tailwind play nice with Vercel

- public.js
- signupV2.ejs
When you sign up and there is an error, it doesn't reset all of the information. So its less annoying and faster
> Changing Signup
